on:
  pull_request:
    types: [opened, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get base branch
        if: github.event.action == 'synchronize'
        run: |
          echo "New base branch: ${{ github.event.pull_request.base.ref }}"
          echo "Old base branch: ${{ github.event.changes.base.from }}"
