name: Check changes (edit PR)

on:
  pull_request:
    types: [opened, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR title
        run: |
          echo "New title: ${{ github.event.pull_request.title }}"
          echo "Old title: ${{ github.event.changes.title.from }}"
      - name: Get base branch
        if: github.event.action == 'edited'
        run: |
          echo "New base branch: ${{ github.event.pull_request.base.ref }}"
          echo "Old base branch: ${{ github.event.changes.base.from }}"
