name: Convert task titles to uppercase

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  convert-tasks:
    runs-on: ubuntu-latest
    steps:
      - name: Update pull request title
        uses: amannn/action-semantic-pull-request@v5
        with:
          types: |
            TASK
            FEATURE
            BUGFIX
          scopes: []
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
