name: Convert task titles to uppercase

on:
  pull_request:
    types: [opened, edited]

jobs:
  convert-tasks:
    runs-on: ubuntu-latest
    steps:
      - name: Check pull request title
        id: check_title
        run: |
          if echo "${{ github.event.pull_request.title }}" | grep -iq "^task:"; then
            echo "::set-output name=title_changed::true"
          else
            echo "::set-output name=title_changed::false"
          fi
      - name: Update pull request title
        if: steps.check_title.outputs.title_changed == 'true'
        uses: peter-evans/update-pull-request-title@v1
        with:
          title: ${{ github.event.pull_request.title ^(?i)task: TASK: }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
