name: Validate PR titles

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  convert-tasks:
    runs-on: ubuntu-latest
    steps:
      - name: Update pull request title
        uses: roseline124/action-semantic-pull-request@v1
        with:
          types: |
            TASK
            FEATURE
            BUGFIX
          requireScope: false
          action: autofix
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
