name: Validate PR title

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  convert-tasks:
    runs-on: ubuntu-latest
    steps:
      - name: Update pull request title
        uses: roseline124/pr-title-convention@v1.0.2
        with:
          types: |
            TASK
            FEATURE
            BUGFIX
          requireScope: false
          action: autofix
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
